name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes triggered by a newly created version tag.'
author: 'Lance Truong'
outputs:
  release-url:
    description: 'The URL of the GitHub drafted release'
runs:
  using: 'node16'
  main: 'dist/index.js'
