name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes triggered by a newly created version tag.'
author: 'Lance Truong'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the current session'
    required: true
outputs:
  release-url:
    description: 'The URL of the GitHub drafted release'
runs:
  using: 'node16'
  main: 'dist/index.js'
